import type { FastifyInstance, FastifyRequest } from 'fastify'
import { randomUUID } from 'node:crypto'
import { DemoStore, errorBody } from '../demo-store.js'
const auth=(r:FastifyRequest,s:DemoStore)=>s.userForToken(String(r.headers.authorization??'').replace(/^Bearer\s+/i,''))
export async function aiRoutes(app: FastifyInstance, store: DemoStore) {
  app.post('/ai/jobs', async (r,reply)=>{const u=auth(r,store), body:any=r.body, ids=body?.material_ids??body?.photo_ids, consent=body?.consent===true;if(!u)return reply.code(401).send(errorBody('TOKEN_INVALID','token invalid'));if(!Array.isArray(ids))return reply.code(400).send(errorBody('BAD_REQUEST','material_ids requires two items'));const unauthorized=ids.some((id:string)=>{const photo=store.photos.get(id);return !photo || (photo.authorId!==u.id && !(consent && store.isFriend(u.id,photo.authorId)))});if(unauthorized)return reply.code(403).send(errorBody('FORBIDDEN','material is not authorized'));if(ids.length<2)return reply.code(400).send(errorBody('BAD_REQUEST','material_ids requires two items'));const id=`job_${randomUUID()}`, job={id,ownerId:u.id,materialIds:ids,status:'queued' as const,createdAt:new Date().toISOString()};store.jobs.set(id,job);setTimeout(()=>{const j=store.jobs.get(id);if(!j)return;j.status='processing';setTimeout(()=>{j.status=ids.includes('fail')?'failed':'completed';if(j.status==='failed')j.error='simulated generation failure'},20)},5);return reply.code(202).send({job_id:id,id,status:job.status,created_at:job.createdAt})})
  app.get('/ai/jobs/:id', async (r,reply)=>{const u=auth(r,store),j=store.jobs.get((r.params as any).id);if(!u)return reply.code(401).send(errorBody('TOKEN_INVALID','token invalid'));if(!j)return reply.code(404).send(errorBody('NOT_FOUND','job not found'));if(j.ownerId!==u.id)return reply.code(403).send(errorBody('FORBIDDEN','not owner'));return {...j,result_url:j.status==='completed' ? `/v1/photos/${j.materialIds[0]}/image` : undefined,message:j.error}})
  app.delete('/ai/jobs/:id/result', async (r,reply)=>{const u=auth(r,store),j=store.jobs.get((r.params as any).id);if(!u)return reply.code(401).send(errorBody('TOKEN_INVALID','token invalid'));if(!j)return reply.code(404).send(errorBody('NOT_FOUND','job not found'));if(j.ownerId!==u.id)return reply.code(403).send(errorBody('FORBIDDEN','not owner'));store.jobs.delete(j.id);return reply.code(204).send()})
}
