import type { FastifyInstance, FastifyRequest } from 'fastify'
import { randomUUID } from 'node:crypto'
import { DemoStore, errorBody } from '../demo-store.js'
import { SimulatorAiProvider, type AiProvider } from '../ai-provider.js'
import type { PhotoStorage } from '../photo-store.js'
const auth=(r:FastifyRequest,s:DemoStore)=>s.userForToken(String(r.headers.authorization??'').replace(/^Bearer\s+/i,''))
export async function aiRoutes(app: FastifyInstance, store: DemoStore, provider: AiProvider = new SimulatorAiProvider(), files?: PhotoStorage) {
  app.post('/ai/jobs', async (r,reply)=>{const u=auth(r,store), body:any=r.body, ids=body?.material_ids??body?.photo_ids, consent=body?.consent===true;if(!u)return reply.code(401).send(errorBody('TOKEN_INVALID','token invalid'));if(!Array.isArray(ids))return reply.code(400).send(errorBody('BAD_REQUEST','material_ids requires two items'));const unauthorized=ids.some((id:string)=>{const photo=store.photos.get(id);return !photo || (photo.authorId!==u.id && !(consent && store.isFriend(u.id,photo.authorId)))});if(unauthorized)return reply.code(403).send(errorBody('FORBIDDEN','material is not authorized'));if(ids.length<2)return reply.code(400).send(errorBody('BAD_REQUEST','material_ids requires two items'));const id=`job_${randomUUID()}`, job={id,ownerId:u.id,materialIds:ids,provider:provider.name,status:'queued' as const,createdAt:new Date().toISOString()};store.jobs.set(id,job);setTimeout(async()=>{const j=store.jobs.get(id);if(!j)return;j.status='processing';try { const result=await provider.generate({ materialIds: ids }); j.status=result.status; j.resultPhotoId=result.resultPhotoId; j.error=result.error } catch (error) { j.status='failed'; j.error=error instanceof Error ? error.message : 'AI provider failed' }},5);return reply.code(202).send({job_id:id,id,status:job.status,provider:job.provider,created_at:job.createdAt})})
  app.get('/ai/jobs/:id', async (r,reply)=>{const u=auth(r,store),j=store.jobs.get((r.params as any).id);if(!u)return reply.code(401).send(errorBody('TOKEN_INVALID','token invalid'));if(!j)return reply.code(404).send(errorBody('NOT_FOUND','job not found'));if(j.ownerId!==u.id)return reply.code(403).send(errorBody('FORBIDDEN','not owner'));return {...j,result_url:j.status==='completed' ? `/v1/photos/${j.resultPhotoId ?? j.materialIds[0]}/image` : undefined,message:j.error}})
  app.post('/ai/jobs/:id/publish', async (r:any,reply)=>{const u=auth(r,store),j=store.jobs.get(r.params.id);if(!u)return reply.code(401).send(errorBody('TOKEN_INVALID','token invalid'));if(!j)return reply.code(404).send(errorBody('NOT_FOUND','job not found'));if(j.ownerId!==u.id)return reply.code(403).send(errorBody('FORBIDDEN','not owner'));if(j.publishedPhotoId){const existing=store.photos.get(j.publishedPhotoId);if(existing)return reply.code(200).send(publishedBody(j,existing));j.publishedPhotoId=undefined}if(j.status!=='completed')return reply.code(409).send(errorBody('AI_NOT_READY','AI result is not ready'));const source=store.photos.get(j.resultPhotoId ?? j.materialIds[0]);if(!source)return reply.code(409).send(errorBody('AI_RESULT_UNAVAILABLE','AI result is unavailable'));const body=r.body??{};const caption=body.caption===undefined?'两份在场，遇见一次。':String(body.caption);const circle=body.circle===undefined?'小圈':String(body.circle);if(caption.length>140||!circle||circle.length>32)return reply.code(400).send(errorBody('BAD_REQUEST','caption must be at most 140 characters and circle must be between 1 and 32 characters'));const photo={...source,id:`p_ai_${randomUUID()}`,authorId:u.id,caption,circle,createdAt:new Date().toISOString(),idempotencyKey:undefined,deviceId:undefined};try { if(files) await files.save(photo) } catch { return reply.code(503).send(errorBody('STORAGE_UNAVAILABLE','photo storage unavailable')) }store.photos.set(photo.id,photo);j.publishedPhotoId=photo.id;return reply.code(201).send(publishedBody(j,photo))})
  app.delete('/ai/jobs/:id/result', async (r,reply)=>{const u=auth(r,store),j=store.jobs.get((r.params as any).id);if(!u)return reply.code(401).send(errorBody('TOKEN_INVALID','token invalid'));if(!j)return reply.code(404).send(errorBody('NOT_FOUND','job not found'));if(j.ownerId!==u.id)return reply.code(403).send(errorBody('FORBIDDEN','not owner'));store.jobs.delete(j.id);return reply.code(204).send()})
}

function publishedBody(job: any, photo: any) { return { photo_id: photo.id, url: `/v1/photos/${photo.id}/image`, created_at: photo.createdAt, caption: photo.caption, circle: photo.circle, source_job_id: job.id } }
