"""Make PlatformIO rebuild main.cpp when the private config metadata changes.

This pre-build hook never opens device_config.h. It records only existence,
mtime_ns, and size in an ignored, non-secret header included by main.cpp.
"""

from pathlib import Path
import os
import tempfile

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.


project_dir = Path(env.subst("$PROJECT_DIR"))  # type: ignore[name-defined]
config_path = project_dir / "include" / "device_config.h"
stamp_path = project_dir / "include" / "device_config_stamp.h"

try:
    metadata = config_path.stat()
    present = 1
    mtime_ns = metadata.st_mtime_ns
    size = metadata.st_size
except FileNotFoundError:
    present = 0
    mtime_ns = 0
    size = 0

stamp = f"""#pragma once
// Generated by tools/config_dependency.py; contains metadata only.
#define PVC_DEVICE_CONFIG_PRESENT {present}
#define PVC_DEVICE_CONFIG_MTIME_NS {mtime_ns}ULL
#define PVC_DEVICE_CONFIG_SIZE {size}ULL
"""

previous = stamp_path.read_text(encoding="ascii") if stamp_path.exists() else None
if previous != stamp:
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="ascii", dir=stamp_path.parent, delete=False
        ) as temporary:
            temporary.write(stamp)
            temporary_path = Path(temporary.name)
        os.replace(temporary_path, stamp_path)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()
