#!/usr/bin/env python3
"""Generate a private device_config.h without storing secrets in the repo."""

from __future__ import annotations

import argparse
import getpass
import ipaddress
import json
import os
from pathlib import Path
import sys
import tempfile
from typing import Optional
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "include" / "device_config.h"


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def local_hostname(hostname: str) -> bool:
    lowered = hostname.lower()
    if lowered == "localhost" or lowered.endswith(".local"):
        return True
    try:
        address = ipaddress.ip_address(lowered)
    except ValueError:
        return False
    if not isinstance(address, ipaddress.IPv4Address):
        return False
    networks = (
        ipaddress.ip_network("10.0.0.0/8"),
        ipaddress.ip_network("127.0.0.0/8"),
        ipaddress.ip_network("172.16.0.0/12"),
        ipaddress.ip_network("192.168.0.0/16"),
    )
    return any(address in network for network in networks)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ssid", required=True)
    password_source = parser.add_mutually_exclusive_group()
    password_source.add_argument(
        "--password", help="Wi-Fi password (interactive prompt is safer)"
    )
    password_source.add_argument(
        "--password-env", metavar="NAME", help="read Wi-Fi password from NAME"
    )
    password_source.add_argument(
        "--open-network", action="store_true", help="explicitly use an empty password"
    )
    parser.add_argument(
        "--api-base", required=True, help="for example https://api.example.com/v1"
    )
    parser.add_argument("--ca-file", type=Path, help="PEM root CA; required for HTTPS")
    parser.add_argument("--allow-local-http", action="store_true")
    parser.add_argument("--force", action="store_true",
                        help="replace an existing device_config.h")
    args = parser.parse_args()

    if args.password_env:
        if args.password_env not in os.environ:
            parser.error(f"environment variable {args.password_env!r} is not set")
        password = os.environ[args.password_env]
    elif args.open_network:
        password = ""
    elif args.password is not None:
        password = args.password
    elif sys.stdin.isatty():
        password = getpass.getpass("Wi-Fi password (empty only for an open network): ")
        confirmation = getpass.getpass("Repeat Wi-Fi password: ")
        if password != confirmation:
            parser.error("Wi-Fi passwords do not match")
    else:
        parser.error(
            "non-interactive use requires --password-env, --password, or --open-network"
        )
    if password == "" and not args.open_network:
        parser.error("an empty Wi-Fi password requires explicit --open-network")

    parsed = urlparse(args.api_base)
    if parsed.scheme not in {"https", "http"} or not parsed.hostname:
        parser.error("--api-base must be an absolute http(s) URL")
    if parsed.username or parsed.password or parsed.query or parsed.fragment:
        parser.error("--api-base must not contain credentials, query, or fragment")
    try:
        parsed.port
    except ValueError as error:
        parser.error(str(error))
    if parsed.scheme == "https" and args.ca_file is None:
        parser.error("HTTPS requires --ca-file")
    if parsed.scheme == "http" and not args.allow_local_http:
        parser.error("HTTP requires --allow-local-http and is rechecked on device")
    if parsed.scheme == "http" and not local_hostname(parsed.hostname):
        parser.error("plain HTTP is allowed only for localhost/private/LAN hosts")

    if OUTPUT.exists() and not args.force:
        if not sys.stdin.isatty():
            parser.error(f"{OUTPUT} exists; use --force to replace it")
        answer = input(f"Replace {OUTPUT}? [y/N] ").strip().lower()
        if answer not in {"y", "yes"}:
            raise SystemExit("not changed")

    ca_pem = args.ca_file.read_text(encoding="utf-8") if args.ca_file else ""
    if ')PVC_CA"' in ca_pem:
        parser.error("CA file contains the reserved raw-string delimiter")

    text = f'''#pragma once
// Generated by tools/configure.py. This file is gitignored.
#define PVC_WIFI_SSID {c_string(args.ssid)}
#define PVC_WIFI_PASSWORD {c_string(password)}
#define PVC_API_BASE_URL {c_string(args.api_base.rstrip('/'))}
#define PVC_TLS_ROOT_CA_PEM R"PVC_CA({ca_pem})PVC_CA"
#define PVC_ALLOW_HTTP_LOCAL_DEV {1 if args.allow_local_http else 0}
'''

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=OUTPUT.parent, delete=False
        ) as temporary:
            temporary.write(text)
            temporary_path = Path(temporary.name)
        temporary_path.chmod(0o600)
        temporary_path.replace(OUTPUT)
        OUTPUT.chmod(0o600)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
